{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  "maven-results-pvc"
  labels:
    {{- include "maven-test.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.pvc.size | default "1Gi" }}
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
{{- end }}